/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407.h"
#include"gpio.h"
#include"spi.h"
#include<string.h>
#include"uart.h"
#include"i2c.h"
#include"otg.h"
#include"timer.h"
#include"adc.h"
#include"eth.h"
#include "eth_hanlde_packet.h"
#include "dns.h"
#include "udp_layer.h" // Nhúng thêm nếu cần gọi các hàm UDP khác
#include "mqtt.h"


uint8_t o;
int k=0;
SPI_Handle_t y;
UART_Handle_t z;
I2C_Handle_t t;
OTG_FS_ConFig_t g;
uint32_t packet[64];
USB_SETUP_PACKET op,pp;
uint8_t mode,pktsts=0,count=0,count1=0;
uint16_t bcnt=0,addr,addr1;
char bufer[11];
uint8_t set_line[7];
uint8_t receive[64];
TIM_Handle_t tim1;
ETH_Handle_t eth;
ADC_Handle_t adc1;
void CLK_init()
{
	    *((__vo uint32_t*)(0x40023C00))&=~(0x7);
		*((__vo uint32_t*)(0x40023C00))|=3;//60-90 mhz for hclk
		//enable hse
		RCC->CR|=1<<16;
		while(!(RCC->CR&(1<<17)));

		//choose PLL entry
		RCC->PLLCFGR|=1<<22;
		//PLL div M
		RCC->PLLCFGR&=~(0x3f);
		RCC->PLLCFGR|=8;//1mhz
		//PLL mul N
		RCC->PLLCFGR&=~(0x1ff<<6);
		RCC->PLLCFGR|=288<<6;//288mhz

		//PLL div q for otg fs 48mhz
		RCC->PLLCFGR&=~(0xf<<24);
		RCC->PLLCFGR|=6<<24;//48mhz
		//PLL div P for sys clock

		RCC->PLLCFGR&=~(0x3<<16);
		RCC->PLLCFGR|=0<<16;//144mhz
		// enable pll
		RCC->CR|=1<<24;
		while(!(RCC->CR&(1<<25)));
		//system clock select
		RCC->CFGR&=~(0x03);
		RCC->CFGR|=2;//pll selected as system clock
		while(((RCC->CFGR>>2)&0x03)!=0x02);//wait system clock sta en pll
		//AHB PRE
		RCC->CFGR&=~(0xf<<4);
		RCC->CFGR|=8<<4;//72mhz
		//APB2
		RCC->CFGR&=~(0x7<<13);
		RCC->CFGR|=4<<13;//36mhz
		//APB1
		RCC->CFGR&=~(0x7<<10);
		RCC->CFGR|=4<<10;//36mhz
}
void ETH_PIN_Init()
{
	GPIO_Handle_t y;
	y.gpiox=GPIOA;
	y.gpioy.mode=GPIO_ALTFUNC;
	//y.gpioy.mode=GPIO_OUTPUT;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.ospeed=GPIO_VRY_HIGH_SPEED;
	y.gpioy.pin=GPIO_PIN_1;//ref_clk
	y.gpioy.alt_num= GPIO_PIN_AF11;
	//y.gpioy.alt_num= GPIO_PIN_AF0;
	GPIO_Init(&y);
	y.gpioy.pin=GPIO_PIN_2;//MDIO
	GPIO_Init(&y);
	y.gpioy.pin=GPIO_PIN_7;// CRS
	GPIO_Init(&y);
	y.gpiox=GPIOB;
	y.gpioy.pin=GPIO_PIN_11;//txen
	GPIO_Init(&y);
	y.gpioy.pin=GPIO_PIN_12;//txd0
	GPIO_Init(&y);
	y.gpioy.pin=GPIO_PIN_13;//txd1
	GPIO_Init(&y);
	y.gpiox=GPIOC;
	//y.gpioy.mode=GPIO_OUTPUT;
	y.gpioy.pin=GPIO_PIN_4;//rxd0
	//y.gpioy.alt_num= GPIO_PIN_AF0;
	GPIO_Init(&y);
	y.gpioy.pin=GPIO_PIN_5;//rxd1
	GPIO_Init(&y);
	y.gpioy.pin=GPIO_PIN_1;//mdc
	GPIO_Init(&y);
}
ETH_Handle_t eth;
uint16_t id2,id3,id1;
__attribute__((aligned(4))) uint8_t tx_buffer[1024];
__attribute__((aligned(4))) uint8_t rx_buffer[1024];
uint32_t test=0;
void config_tx_buffer(ETH_DMADescTypeDef * txbuf, uint32_t buffer_addr, uint32_t next_desc_addr)
{
    txbuf->Buffer1Addr = buffer_addr;           // Word 2: Trỏ tới data thực tế
    txbuf->Buffer2NextDescAddr = next_desc_addr; // Word 3: Trỏ tới Descriptor kế tiếp

    // Word 1: Quy định kích thước và bật tính năng Chained (bit 20)
    txbuf->ControlBufferSize = 1024 | (1UL << 20);

    // Word 0: Nhượng quyền cho DMA
    txbuf->Status |= (1UL << 31) | (1UL << 29) | (1UL << 28);
}
void config_rx_buffer(ETH_DMADescTypeDef * rxbuf, uint32_t buffer_addr, uint32_t next_desc_addr)
{
    rxbuf->Buffer1Addr = buffer_addr;           // Word 2: Vùng RAM để DMA ghi gói tin vào
    rxbuf->Buffer2NextDescAddr = next_desc_addr; // Word 3: Trỏ tới Descriptor tiếp theo (hoặc chính nó)

    // Word 1: Buffer size 1536 và bật bit RCH (bit 14) cho Second Address Chained
    rxbuf->ControlBufferSize = 1024 | (1UL << 14);

    // Word 0: BẮT BUỘC set bit OWN (bit 31) = 1 cho Rx ngay từ đầu
    rxbuf->Status = (1UL << 31);
}
void ETH_INIT()
{
	eth.eth_mac=ETH_MAC;
	eth.eth_mmc=ETH_MMC;
	eth.eth_ieee=ETH_IEEE;
	eth.eth_dma=ETH_DMA;
	eth.eth_x.mode=ETH_RMII_MODE;
	eth.eth_x.phy_addr=1;
	eth.eth_x.mac_addr= 0x000100000002;
	eth.eth_x.ip_addr=0xC0A88932;//0xA9FEA9FE;
	eth.TX_BUFFER= (uint32_t*)(0x2001C000);
	eth.RX_BUFFER= (uint32_t*)(0x2001C800);
	eth.tx_state=IDLE;
	eth.rx_state=IDLE;
	config_tx_buffer(eth.TX_BUFFER,(uint32_t)tx_buffer,(uint32_t)eth.TX_BUFFER);
	config_rx_buffer(eth.RX_BUFFER, (uint32_t)rx_buffer, (uint32_t)eth.RX_BUFFER);
	ETH_Init(&eth);

	NVIC_ConFig(61,ENABLE);
	NVIC_PRIORITY(61,1);
}
void adc_init()
{
	adc1.adcx=ADC1;
	adc1.adcy.channel=8;
	adc1.adcy.resolution=0;
	adc1.adcy.cycle=6;
	adc1.adcy.rank=1;
	ADC_Init(&adc1);
	GPIO_Handle_t x;
	x.gpiox=GPIOB;
	x.gpioy.mode= GPIO_ANALOG_MODE;
	x.gpioy.optype=GPIO_OUTPUT_PP;
	x.gpioy.ospeed= GPIO_VRY_HIGH_SPEED;
	x.gpioy.pin=0;
	x.gpioy.alt_num=GPIO_PIN_AF0;
	x.gpioy.pupd=GPIO_NO_PUPD;
	GPIO_Init(&x);
}
uint16_t length;
__attribute__((aligned(4))) ETH_REI_DATA *rx_buff;
uint8_t type;uint16_t bufff[1];
int main(void)
{
	CLK_init();
	ETH_PIN_Init();
	ETH_INIT();
	adc_init();
	GPIO_Handle_t y;
	y.gpiox=GPIOC;
	y.gpioy.mode=GPIO_OUTPUT;
	y.gpioy.optype=GPIO_OUTPUT_PP;
	y.gpioy.ospeed=GPIO_VRY_HIGH_SPEED;
	y.gpioy.pin=GPIO_PIN_6;//ref_clk
	y.gpioy.alt_num= GPIO_PIN_AF0;
	GPIO_Init(&y);

	/* --- CẤU HÌNH CÁC THÔNG SỐ INTERNET MẠNG --- */
	// 1. Địa chỉ DNS Server toàn cầu của Google: 8.8.8.8
	uint32_t dns_server_ip = 0x08080808;

	// 2. LƯU Ý CỰC KỲ QUAN TRỌNG: MAC của Cổng Router (Default Gateway) nhà bạn.
	// Vì gói tin DNS phải bay ra Internet nên bắt buộc phải đi qua Router.
	// Bạn mở CMD trên máy tính gõ "arp -a" để xem MAC của Router nhà mình là gì rồi điền vào đây nhé.
	//uint8_t router_mac[6] = {0x14, 0x4D, 0x67, 0x11, 0x22, 0x33}; // <--- THAY BẰNG MAC ROUTER THẬT
	uint8_t router_mac[6] = {0x00, 0xE0, 0x4C, 0x68, 0x01, 0xAA};
	//uint8_t router_mac[6] = {0x08, 0x8F, 0xC3, 0x63, 0x34, 0xE4};
	/* --- BẮT ĐẦU KÍCH HOẠT DNS --- */
	// Khởi tạo tầng DNS
	TCP_Layer_Init();

	DNS_Init(dns_server_ip, router_mac);
	// Ra lệnh bắn câu hỏi: "Ê Google, broker.hivemq.com là IP mấy?"
	DNS_Start_Query(&eth, "mqtt.thingsboard.cloud");
	for(int i=0;i<100000;i++);


	while (1)
	{
		ETH_TYPE(&eth);
	    // Hàm xử lý nhận dữ liệu từ chip Ethernet của bạn (vẫn phải chạy liên tục)
	    // Ví dụ tên hàm của bạn có thể là ETH_Process_Rx_Packets(&eth_handle);
	    // Hoặc xử lý trong Ngắt (IRQ) tùy kiến trúc code của bạn.
		if(mqtt_client.state<=MQTT_STATE_CONNECTED)
		ADC_Read(ADC1, 1, bufff);
	    /* --- KIỂM TRA MÁY TRẠNG THÁI DNS --- */
	    switch (DNS_Get_State())
	    {
	        case DNS_STATE_QUERYING:
	            // Đang chờ gói tin phản hồi từ Server, không làm gì cả, cứ để mạch chạy tiếp
	            break;

	        case DNS_STATE_SUCCESS:
	            {
	                uint32_t ip_ket_qua = DNS_Get_Resolved_IP();
	                mqtt_client.broker_ip=(ip_ket_qua);
	                MQTT_Init(&eth, "mqtt.thingsboard.cloud", 1883);
	               // dns_state=DNS_STATE_IDLE;
	                DNS_Set_State(DNS_STATE_IDLE);

	                // NẾU CHẠY MẠCH THẬT:
	                // Bạn đặt một Breakpoint tại đây! Khi debug, nếu mạch nhảy được vào đây
	                // và biến "ip_ket_qua" hiện lên dạng số (Ví dụ: 0x2223A1B2...)
	                // tức là STM32 của bạn đã phân giải Tên Miền thành IP thành công 100%!

	                // Sau khi có IP này rồi, bạn có thể nạp nó vào struct kết nối TCP
	                // để bắt đầu làm trò kết nối MQTT tới HiveMQ bét nhè luôn.

	                // (Tùy chọn) Chuyển trạng thái về IDLE để không nhảy vào đây liên tục nữa
	                // DNS_Init(dns_server_ip, router_mac);
	            	//extern dns_state = DNS_STATE_IDLE;
	            }
	            break;

	        case DNS_STATE_ERROR:

	            // Nếu đen đủi rơi vào đây, có thể do: Sai tên miền, Router chặn, hoặc mất mạng.
	            // Bạn có thể cho gửi lại câu hỏi sau 5 giây nếu muốn chống nhiễu mạng.
	            break;

	        default:
	            break;
	    }
	    MQTT_Handle(&eth,mqtt_client.state);
	}
}
void ETH_IRQHandler ()
{
	ETH_IRQ_Handle(&eth);

}
